### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuuritaly** [gojibjib/jibjib-model#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by obitech** [comment]
Hey Zuur, thank you so much for your offer! We appreciate any help offered :) However, @amuenz has already done a fantastic job designing a logo, which you can see on our organization page. Right now we're discussing where to take this project from here and I'm sure there will be lots of additional design work coming up the future. I'm sure we can we work together on something, very happy to stay in touch with you!!
