### ISSUE TITLE
Bird Sound Dataset

### ISSUE THREAD

**Issue by LK1711** [gojibjib/jibjib-model#4]
Hi there!

How is the rep downloading the Input dataset? Or is it to be manually downloaded?

Thanks for you help!

**Comment by obitech** [comment]
Hey, sorry the dataset is not included or available online for now. The one we trained with is quite large (130GB) and we haven't had a chance to upload this amount of data yet. There are some scripts we have used to create the data set in the [gojibjib/voice-grabber](https://github.com/gojibjib/voice-grabber) repo, but I have to admit that there isn't a clear path or pipeline to grab the whole data set at the moment. You will have to check the code yourself and make adjustments where necessary. Sorry about that.

We're considering putting it on Kaggle and I hope to upload our whole data set pipeline at the beginning of 2019. I will close this issue for now, but will post updates here as soon as there are new developments.
