### ISSUE TITLE
Explore Options for funding

### ISSUE THREAD

**Issue by obitech** [gojibjib/jibjib-model#5]
We need to explore options on how pay for training our model. There are several options:

- [ ] Talk to Coding Davinci again
- [ ] Talk to Stefan @ TUC
- [ ] Talk to Museum in Berlin
- [ ] Talk to some companies

**Comment by obitech** [comment]
@pplitzner going to talk to his friend if we can get his support

**Comment by obitech** [comment]
I'll try to talk to Coding Davinci & MFN

**Comment by pplitzner** [comment]
Oracle just released a free-tier ML service: 
https://www.heise.de/developer/meldung/Oracle-OpenWorld-Datenbank-und-Cloud-Infrastruktur-als-Always-Free-Angebot-4525667.html?wt_mc=rss.developer.beitrag.atom

I also asked my friend. His company uses Google for ML trainings which also has a free tier with about 30 test runs for free. The company itself does not provide clusters to train on.

**Comment by obitech** [comment]
Unfortunately Oracle's free tier is nowhere near enough compute power:

> 2 virtual machines with 1/8 OCPU and 1 GB memory each.

Do you know which specific service they use from Google Cloud? I know there is [Google Colab](https://colab.research.google.com/notebooks/welcome.ipynb) but I couldn't find anything related to ML on GCP's [Always Free](https://cloud.google.com/free/docs/gcp-free-tier#always-free) tier.

**Comment by pplitzner** [comment]
> Do you know which specific service they use from Google Cloud? I know there is [Google Colab](https://colab.research.google.com/notebooks/welcome.ipynb) but I couldn't find anything related to ML on GCP's [Always Free](https://cloud.google.com/free/docs/gcp-free-tier#always-free) tier.

Not sure. He just told me to look at the Google Services
